[package]
name = "FatFile"
version = "0.1.0"
edition = "2024"

[dependencies]
chardet = "0.2.4"
encoding_rs = "0.8.35"
memchr = "2.7.6"
once_cell = "1.21.3"
rayon = "1.11.0"
regex = "1.12.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
